# Generated by Django 4.2 on 2023-08-05 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tweets", "0004_tweet_timestamp_alter_tweet_user_tweetlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="tweet_user",
                through="tweets.TweetLike",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
