# Generated by Django 4.2 on 2023-08-06 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0005_tweet_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tweets.tweet",
            ),
        ),
    ]
