# Generated by Django 4.2 on 2023-08-15 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0007_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
