# Generated by Django 4.2 on 2023-08-19 10:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tweets", "0008_delete_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tweetlike",
            unique_together={("user", "tweet")},
        ),
    ]
