version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:
  backend:
    tty: true
    restart : always
    ports:
     - "8000:8000"
    command: ["./tweetme/build/entrypoint.sh"]
    build:
     context: ./tweetme
     dockerfile: ./build/Dockerfile
    networks:
      - mynetwork
  
  frontend:
    build:
      context: .
      dockerfile: client-side/Dockerfile
    volumes:
      - ./client-side:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "start"]

