# Generated by Django 4.2 on 2023-08-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usertesster", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
