# Generated by Django 4.2 on 2023-08-16 05:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usertesster", "0003_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
    ]
