# Generated by Django 4.2 on 2023-08-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usertesster", "0004_remove_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
