# Generated by Django 4.2 on 2023-08-16 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("usertesster", "0007_rename_user_userprofile_user_base"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user_base",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
