# Generated by Django 4.2 on 2023-08-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usertesster", "0008_remove_userprofile_user_base_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
