# Generated by Django 4.2 on 2023-08-19 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usertesster", "0010_userfollower_user_follower"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userfollower",
            unique_together={("user", "follower")},
        ),
    ]
