# Generated by Django 4.2 on 2023-08-19 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usertesster", "0015_alter_userfollower_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="follower",
        ),
        migrations.DeleteModel(
            name="UserFollower",
        ),
    ]
