# Generated by Django 4.2 on 2023-08-20 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usertesster", "0020_alter_userfollowing_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserFollowing",
        ),
    ]
